import "./_styles/globals.css";
export const metadata = {
  title: "Welcome to Axben",
  description: "Generated by Osahon",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
